name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      
      - name: Execute tests
        run: vendor/bin/phpunit
